# Generated by Django 5.0.4 on 2024-05-03 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News_Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('summary', models.TextField()),
                ('content', models.TextField()),
                ('published', models.CharField(max_length=500)),
                ('pub_date', models.DateField()),
                ('cat', models.CharField(max_length=500)),
                ('author', models.TextField()),
            ],
        ),
    ]
