# Generated by Django 5.0.4 on 2024-05-03 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News_Articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news_article',
            old_name='cat',
            new_name='category',
        ),
    ]
