# Generated by Django 5.0.4 on 2024-05-05 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News_Articles', '0004_rename_authors_author_rename_categories_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='authors',
            new_name='author',
        ),
    ]
