# Generated by Django 5.0.4 on 2024-05-05 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News_Articles', '0005_rename_authors_author_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.TextField(),
        ),
    ]
