# Generated by Django 5.0.6 on 2024-05-08 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News_Articles', '0007_rename_author_author_uni_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='news_article',
            name='link',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
